### ISSUE TITLE
Cannot create character

### ISSUE THREAD

**Issue by panmarco83** [AbyssEngine/OpenDiablo2#43]
I managed to get the engine to run ( [see here](https://github.com/AbyssEngine/OpenDiablo2/issues/38#issuecomment-1235532801) ), but now I cannot create any characters at all:  
![image](https://user-images.githubusercontent.com/67251243/188164705-36f70d0b-71e4-4851-b301-7cff098b1165.png)  
First: you can't enter or change the character name.  
Second: you can't continue even with the default name in place.

**Comment by DarthGandalf** [comment]
This is not implemented yet :)

**Comment by panmarco83** [comment]
> This is not implemented yet :)

D'oh....
Okay, sort of felt like it had come to the point of play-ability with how well the launch and menu's were working.
My bad.
Very much looking forward to more advancements, good luck devs :smiley:

**Comment by panmarco83** [comment]
> This is not implemented yet :)

D'oh....
Okay, sort of felt like it had come to the point of play-ability with how well the launch and menu's were working.
My bad.
Very much looking forward to more advancements, good luck devs :smiley:
