### ISSUE TITLE
dsp: No such audio device

### ISSUE THREAD

**Issue by DarthGandalf** [AbyssEngine/OpenDiablo2#44]
I managed to get it to run on Arch Linux, I needed to compile the engine from source (as of 2022.09.02) and copy the binary's and the libraries over the ones provided by the release files.
I was getting the same error message as seen above this message:  
```[2022-09-02 15:30:23.960] [critical] [abyssengine.cpp:85] Caught exception St13runtime_error: dsp: No such audio device```  
So compiling allowed me to start the game, BUT now there is another problem that halts any possible game play (as far as I can see)  
#43

_Originally posted by @panmarco83 in https://github.com/AbyssEngine/OpenDiablo2/issues/38#issuecomment-1235532801_

**Comment by DarthGandalf** [comment]
It works with ALSA for me (I'm compiling on Gentoo)

How did you manage to compile it with OSS?

**Comment by panmarco83** [comment]
I didn't, that was the error message I was getting from the binary for linux in the releases section here.
After I cloned the repository and installed the missing libraries it complained about, it compiled just fine and ran just fine as well.

**Comment by DarthGandalf** [comment]
That just means that we should remove the linux prebuilt binary. At least until a bigger part of the game is implemented, and reintroduce it then not as a binary, but as appimage/flatpack, because not every linux is ubuntu
